### ISSUE TITLE
选中图片后，我要拿到图片展示的正确姿势是什么？

### ISSUE THREAD

**Issue by sandsame** [jianlong108/ImagePicker#1]

**Comment by jianlong108** [comment]
首先感谢朋友的支持,多谢...

你说的问题....流程:

**Comment by sandsame** [comment]
多谢楼主回答，看到了，解决问题了，我以为需要自己通过assetUrl和系统api拿到图片
 dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
          
           @try {
               ALAsset *asset = (ALAsset *)obj.asset;
               ALAssetRepresentation *rep = [asset defaultRepresentation];
               CGImageRef iref = [rep fullScreenImage];
               UIImage *fullScreenImage;
               if (iref) {
                   fullScreenImage = [UIImage imageWithCGImage:iref];
                   self.testImageView.image = fullScreenImage;
              }               
          } @catch (NSException *e) {
              dispatch_async(dispatch_get_main_queue(), ^{
               });
          }
//           
       });
